theme: jekyll-theme-minimal
title: Open Scholarship Zine
logo: https://fcandreu.github.io/openscholarshipzine/IMG_0012.PNG
description: During an OpenCon2018 unconference session, we discussed using the medium of zines to open conversations around decolonizing open scholarship. This project was developed as a result. <br> <a href="tensteps.html">The 10 Steps</a>
